# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts. - maybe use this to specify something like Python version?
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to build'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Install dependencies and build pyinstaller bootloader
      run: choco install -y python3 git ; python3 --version ; choco list --local-only --exact python3 --trace ; dir C:\ProgramData\chocolatey\lib\python3\ ; which python3
