# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts. - maybe use this to specify something like Python version?
    inputs:
      software_version:
        description: 'Version to build'
        default: 'master'
        required: true
      python_version:
        description: 'Python version to use'
        default: '3.10'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ github.event.inputs.python_version }}
        architecture: 'x64'
    # Runs a single command using the runners shell
    - name: Check Python Version
      run: python --version ; pip --version
    - name: Install build dependencies
      run: choco install -y git wget 
    - name: Package installer
      run: wget "https://jrsoftware.org/download.php/is.exe?site=1" -o innosetup.exe ; dir ; .\innosetup.exe /SILENT
