# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts. - maybe use this to specify something like Python version?
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Python Version'
        # Default value if no value is explicitly provided
        default: '3.8.10'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Install python
  #    run: echo "Hello ${{ github.event.inputs.name }}"
      run: echo "Python: "$(python3 --version) && sudo git clone -b v5.0.1 https://github.com/pyinstaller/pyinstaller.git && cd pyinstaller && python3 ./waf all
      
      
