# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts. - maybe use this to specify something like Python version?
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to build'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Install dependencies and build pyinstaller bootloader
      run: choco install -y python3 visualstudio2019-workload-vctools git ; python3 --version
    - name: Build pyinstaller bootloader 
      run: git clone -b v5.0.1 https://github.com/pyinstaller/pyinstaller.git ; cd pyinstaller/bootloader ; python3 ./waf all ; cd .. ; pip3 install wheel ; pip3 install -r requirements.txt ; python3 setup.py install ; pyinstaller --version
    - name: Package?
      run: git clone -b ${{ github.event.inputs.version }} https://github.com/kco-uga/ASpace_Batch_Export-Cleanup-Upload.git ; cd ASpace_Batch_Export-Cleanup-Upload ; pyinstaller -wF as_xtf_GUI.py -n ASpace_Batch_Exporter${{ github.event.inputs.version }} --icon=thumbnail.ico --clean
    - name: Try to make files available as artifacts - spec
      uses: actions/upload-artifact@v3
      with:
          name: specfile
          path: ASpace_Batch_Exporter1.5.0.spec
    - name: Try to make files available as artifacts - build_dir
      uses: actions/upload-artifact@v3
      with:
          name: build_dir
          path: build
    - name: Try to make files available as artifacts - dist_dir
      uses: actions/upload-artifact@v3
      with:
          name: dist_dir
          path: dist
    - name: Try to make files available as artifacts - spec
      uses: actions/upload-artifact@v3
      with:
          name: pycache_dir
          path: __pycache__
